global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "my-app"
    scrape_interval: 5s
    metrics_path: /q/metrics
    static_configs:
      - targets: ["monitoring-and-profiling:8080"]